export type NodeKind =
  | "source"
  | "entityType"
  | "record"
  | "metric"
  | "rule"
  | "knowledge"
  | "agent"
  | "output";

export type LayerId =
  | "sources"
  | "structure"
  | "meaning"
  | "knowledge"
  | "agents"
  | "outputs";

export type OntologyNode = {
  id: string;
  kind: NodeKind;
  label: string;
  sublabel?: string;
  layer: LayerId;
  /** Base position (before layout jitter). Uses right-handed Y-up coordinates. */
  position: [number, number, number];
};

/** Named relationship verbs — mirror PRD §04:
 *  places, maps to, calculated from / aggregates, applies to / filters, uses,
 *  generated by. `instanceOf` is a schema-level "is a" (record → entity type). */
export type EdgeVerb =
  | "instanceOf"
  | "placed"
  | "for"
  | "mapsTo"
  | "aggregates"
  | "filters"
  | "explains"
  | "uses"
  | "generatedBy";

export type OntologyEdge = {
  id: string;
  source: string;
  target: string;
  verb: EdgeVerb;
};

/**
 * Revenue scenario from the PRD §08. Deterministic layout: layers are stacked
 * along Y (sources at the bottom, outputs at the top). All names/records are
 * fictional. Money in NPR, one row per order.
 */
export const revenueNodes: OntologyNode[] = [
  // Sources — where the data originates (raw files)
  { id: "src-customers", kind: "source", label: "customers.csv", sublabel: "CRM export", layer: "sources", position: [-5.6, -6.6, 0.8] },
  { id: "src-orders", kind: "source", label: "orders.csv", sublabel: "OMS export", layer: "sources", position: [-1.2, -6.6, -0.6] },
  { id: "src-products", kind: "source", label: "products.csv", sublabel: "PIM export", layer: "sources", position: [3.6, -6.6, 0.4] },

  // Structure — tables / entity types
  { id: "et-customer", kind: "entityType", label: "Customer", sublabel: "Entity type", layer: "structure", position: [-6.2, -2.5, 0] },
  { id: "et-order", kind: "entityType", label: "Order", sublabel: "Entity type", layer: "structure", position: [-2.2, -2.5, 0] },
  { id: "et-product", kind: "entityType", label: "Product", sublabel: "Entity type", layer: "structure", position: [1.8, -2.5, 0] },

  // Meaning — records (business entities) + metrics
  { id: "c-001", kind: "record", label: "C001", sublabel: "Customer", layer: "meaning", position: [-7.6, -1.4, 1.2] },
  { id: "c-002", kind: "record", label: "C002", sublabel: "Customer", layer: "meaning", position: [-6.0, -1.4, -1.2] },
  { id: "c-003", kind: "record", label: "C003", sublabel: "Customer", layer: "meaning", position: [-4.4, -1.4, 1.0] },

  { id: "o-001", kind: "record", label: "O001", sublabel: "12,000 · Paid", layer: "meaning", position: [-3.4, -1.6, 1.6] },
  { id: "o-002", kind: "record", label: "O002", sublabel: "8,000 · Paid", layer: "meaning", position: [-2.2, -1.6, -1.2] },
  { id: "o-003", kind: "record", label: "O003", sublabel: "5,000 · Cancelled", layer: "meaning", position: [-1.0, -1.6, 1.4] },
  { id: "o-004", kind: "record", label: "O004", sublabel: "15,000 · Paid", layer: "meaning", position: [0.2, -1.6, -1.0] },

  { id: "m-revenue", kind: "metric", label: "M001 · Revenue", sublabel: "NPR 35,000", layer: "meaning", position: [2.4, 1.4, 0] },
  { id: "m-count", kind: "metric", label: "M002 · Paid Orders", sublabel: "3", layer: "meaning", position: [0.0, 2.0, 1.4] },
  { id: "m-avg", kind: "metric", label: "M003 · Avg Paid", sublabel: "NPR 11,666.67", layer: "meaning", position: [-1.8, 1.4, -1.6] },

  // Knowledge — rules + contextual material
  { id: "r-paid", kind: "rule", label: "R001", sublabel: "Paid orders only", layer: "knowledge", position: [4.6, 0.6, 1.8] },
  { id: "k-cancel", kind: "knowledge", label: "Cancellation policy", sublabel: "Why paid only", layer: "knowledge", position: [5.4, 1.8, -0.6] },

  // Agents — agent definitions
  { id: "a-analyst", kind: "agent", label: "Revenue Analyst", sublabel: "Scripted agent", layer: "agents", position: [6.4, 3.4, 0.8] },

  // Outputs — runs / reports
  { id: "out-report", kind: "output", label: "Run · Revenue Report", sublabel: "Snapshot v1", layer: "outputs", position: [4.4, 4.8, -0.6] },
];

export const revenueEdges: OntologyEdge[] = [
  // Sources maps to entity types (structure)
  { id: "e-src-cust-et", source: "src-customers", target: "et-customer", verb: "mapsTo" },
  { id: "e-src-ord-et", source: "src-orders", target: "et-order", verb: "mapsTo" },
  { id: "e-src-prod-et", source: "src-products", target: "et-product", verb: "mapsTo" },

  // Records are instances of entity types
  { id: "e-c1-t", source: "c-001", target: "et-customer", verb: "instanceOf" },
  { id: "e-c2-t", source: "c-002", target: "et-customer", verb: "instanceOf" },
  { id: "e-c3-t", source: "c-003", target: "et-customer", verb: "instanceOf" },
  { id: "e-o1-t", source: "o-001", target: "et-order", verb: "instanceOf" },
  { id: "e-o2-t", source: "o-002", target: "et-order", verb: "instanceOf" },
  { id: "e-o3-t", source: "o-003", target: "et-order", verb: "instanceOf" },
  { id: "e-o4-t", source: "o-004", target: "et-order", verb: "instanceOf" },

  // Orders placed by customers
  { id: "e-o1-c", source: "o-001", target: "c-001", verb: "placed" },
  { id: "e-o2-c", source: "o-002", target: "c-001", verb: "placed" },
  { id: "e-o3-c", source: "o-003", target: "c-002", verb: "placed" },
  { id: "e-o4-c", source: "o-004", target: "c-003", verb: "placed" },

  // Rule / knowledge
  { id: "e-r-filter", source: "r-paid", target: "et-order", verb: "filters" },
  { id: "e-k-r", source: "k-cancel", target: "r-paid", verb: "explains" },

  // Metrics
  { id: "e-m1-o", source: "m-revenue", target: "et-order", verb: "aggregates" },
  { id: "e-m1-r", source: "m-revenue", target: "r-paid", verb: "uses" },
  { id: "e-m2-o", source: "m-count", target: "et-order", verb: "aggregates" },
  { id: "e-m2-r", source: "m-count", target: "r-paid", verb: "uses" },
  { id: "e-m3-m1", source: "m-avg", target: "m-revenue", verb: "uses" },
  { id: "e-m3-m2", source: "m-avg", target: "m-count", verb: "uses" },

  // Agent
  { id: "e-a-m1", source: "a-analyst", target: "m-revenue", verb: "uses" },
  { id: "e-a-k", source: "a-analyst", target: "k-cancel", verb: "uses" },

  // Output
  { id: "e-out-a", source: "out-report", target: "a-analyst", verb: "generatedBy" },
  { id: "e-out-m1", source: "out-report", target: "m-revenue", verb: "uses" },
];

/** Verb display: PRD-style human-readable form. */
export const verbLabel: Record<EdgeVerb, string> = {
  instanceOf: "instance of",
  placed: "placed",
  for: "for",
  mapsTo: "maps to",
  aggregates: "aggregates",
  filters: "filters",
  explains: "explains",
  uses: "uses",
  generatedBy: "generated by",
};
